-- =====================================================================
-- ADC Outbound Performance Board — customer contact list
-- =====================================================================
-- Generated from the live Supabase project (public schema) on 2026-08-26.
-- Run in Supabase > SQL Editor, after schema.sql. Idempotent.
--
-- This is the table the Database view reads, filters, and dispositions.
-- Schema only — no rows. Load your own contacts via the app's CSV import
-- (Admin > Database > Import) or a `copy` from your own export.
--
-- PII WARNING ---------------------------------------------------------
-- Rows in this table hold customer name, phone, email, and street address.
-- Never commit a data export of this table to the repository, and note that
-- the RLS policy below leaves it fully readable and deletable by anyone
-- holding the publishable key. See README.md.
-- ---------------------------------------------------------------------

create table if not exists adc_database(
  id          bigint generated by default as identity primary key,
  segment     text not null,          -- source tab / campaign the row came from
  phone       text,
  customer    text,
  email       text,
  address     text,
  location    text,
  job_ref     text,                   -- CRM job number, when the row has one
  crm_status  text,
  disposition text,                   -- outcome set by the agent in the app
  attempts    int not null default 0,
  agent       text,                   -- outbound agent who worked the row
  notes       text,
  updated_at  timestamptz not null default now()
);

-- The Database view filters on these three columns.
create index if not exists adc_db_segment_idx     on adc_database(segment);
create index if not exists adc_db_phone_idx       on adc_database(phone);
create index if not exists adc_db_disposition_idx on adc_database(disposition);

alter table adc_database enable row level security;

drop policy if exists anon_all on adc_database;
create policy anon_all on adc_database for all using(true) with check(true);


-- =====================================================================
-- Repair: adc_database predating the `id` column
-- =====================================================================
-- The Database view can only edit dispositions when the table has a primary
-- key. Databases created by an early version of this file have no `id`
-- column; this block adds one. It is a no-op everywhere else.

do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name   = 'adc_database'
      and column_name  = 'id'
  ) then
    alter table adc_database add column id bigint generated by default as identity;
    alter table adc_database add constraint adc_database_pkey primary key (id);
  end if;
end $$;
